name = "grade3-fund-maec"
compatibility_date = "2024-11-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "grade3-fund"
database_id = "bacc7ddb-a2cc-4c73-adec-bc70bd5db9cd"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "grade3-fund-receipts"
