name = "grade3-fund-maec"
compatibility_date = "2024-11-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "grade3-fund"
database_id = "b61191eb73cd63812d3b7045744578e5"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "grade3-fund-receipts"
